Unwind assets
GregTheGreek/Element-Finance-Scripts pull request #15
Opened 2023-08-08 07:58 UTC by villanuevawill

## GSC Proposal
The GSC treasury lives in a gnosis safe. // 0x654be0b5556f8eadbc2d140505445fa32715ef2b
Fees on swaps were sent to the safe address. This proposal unwinds all assets >= $400 in value, which is a total of 17 positions. It withdraws from Balancer, redeems the associated principal token, then transfers the assets (base and CRV lp) to the DAO main treasury. This is accomplished in one multisend transaction through the gnosis safe. A tenderly transaction can be reviewed here:

https://dashboard.tenderly.co/shared/simulation/f6442943-d768-4099-ae27-972d59c32ada

To generate the call data for the transaction to the multisend contract, run the gsc treasury test:
`npx hardhat test  egps/egp-16/gsc-treasury-test.ts`

Running the test will generate all the necessary information to verify:
<img width="482" alt="image" src="https://github.com/GregTheGreek/Element-Finance-Scripts/assets/7415822/f8abc83a-9b0c-4571-8f12-f7ed502bc19d">

## Main Treasury Part 1
The main treasury received affiliate rewards via yearn. // 0x82ef450fb7f06e3294f2f19ed1713b255af0f541
We will need two subsequent votes and proposals after this one. The first step is to withdraw each of the yearn positions into associated CRV or base assets. Part 2 will withdraw from the remaining CRV positions. Part 3 will withdraw from curve meta pools and do any necessary swaps (EURS/BTC) via milkman.

To generate the transactions necessary for the call data:
`npx hardhat test  egps/egp-16/main-treasury-test.ts`

Running the test will generate all the necessary information to verify:
<img width="379" alt="image" src="https://github.com/GregTheGreek/Element-Finance-Scripts/assets/7415822/3e842534-fc86-42c2-b600-bc9815454b2f">

2023-08-08 07:58 UTC, villanuevawill commented
@mcclurejt @GregTheGreek - this is ready for review.

2023-08-15 16:02 UTC, GregTheGreek commented
looking over, will take a day or two before i ask questions

2023-08-22 03:12 UTC, cashd reviewed
Just took a pass on this! Definitely should get John or Greg to take a look as they have more experience crafting proposals. Only one major suggestion, I think it is good practice to revoke approvals at the end of the calls.

2023-08-22 03:12 UTC, cashd commented on egps/egp-16/egp-16-main-part-1.ts
> +   * Param BytesLike[] - An arrary of encoded calldata
typo `array`

2023-08-22 03:12 UTC, cashd commented on egps/egp-16/egp-16-main-part-1.ts
> +   * Creates the expiery for the proposal, no need to modify.
`expiry`

2023-08-22 03:12 UTC, cashd commented on egps/egp-16/egp-16-main-part-1.ts
> +    [FrozenLockingVaultProxy, FrozenVestingVaultProxy], // Forzen vaults because all ELFI lives there
`frozen`

2023-08-22 03:12 UTC, cashd commented on egps/egp-16/egp-16-gsc.ts
> +   * - Simple add the multiple call hashes into the array.
`Simply`

2023-08-22 03:12 UTC, cashd commented on egps/egp-16/egp-16-gsc.ts
> +    [addresses.GSCVault], // Forzen vaults because all ELFI lives there
`Frozen`

2023-08-22 10:19 UTC, mcclurejt reviewed
Tests run! Don't see any problems as of yet but will give it one more look through.

Only question is whether any of these positions are in danger of costing more to liquidate than they're worth... any with extremely limited liquidity or low value?

2023-08-23 19:25 UTC, GregTheGreek requested changes
Address Cash's comments and this lgtm

2023-08-24 15:08 UTC, mcclurejt approved these changes
LGTM

2023-09-18 17:54 UTC, villanuevawill commented
> Tests run! Don't see any problems as of yet but will give it one more look through.
> 
> Only question is whether any of these positions are still in danger of costing more to liquidate than they're worth... any with extremely limited liquidity or low value?

I only did positions > $400 for this reason.

2023-09-18 17:55 UTC, villanuevawill commented
> Just took a pass on this! Definitely should get John or Greg to take a look as they have more experience crafting proposals. Only one major suggestion, I think it is good practice to revoke approvals at the end of the calls.

2023-09-18 18:26 UTC, villanuevawill commented
I added revoking of approvals and fixed all typos.

2023-09-18 18:41 UTC, villanuevawill commented
Readme included!

2023-09-19 15:12 UTC, GregTheGreek approved these changes
LGTM

2023-10-10 19:50 UTC, villanuevawill commented
MAIN:

["0xe63697c80000000000000000000000000000000000000000000000004f9d20796e58b53400000000000000000000000082ef450fb7f06e3294f2f19ed1713b255af0f54100000000000000000000000000000000000000000000000000000000000003e8","0xe63697c80000000000000000000000000000000000000000000001b4b53b0499124e04c000000000000000000000000082ef450fb7f06e3294f2f19ed1713b255af0f54100000000000000000000000000000000000000000000000000000000000003e8","0xe63697c800000000000000000000000000000000000000000000002601b67f57cce87f2000000000000000000000000082ef450fb7f06e3294f2f19ed1713b255af0f54100000000000000000000000000000000000000000000000000000000000003e8","0xe63697c8000000000000000000000000000000000000000000000942a0b1f7551f52d9b000000000000000000000000082ef450fb7f06e3294f2f19ed1713b255af0f54100000000000000000000000000000000000000000000000000000000000003e8","0xe63697c800000000000000000000000000000000000000000000042349b1b68254dfe5d000000000000000000000000082ef450fb7f06e3294f2f19ed1713b255af0f54100000000000000000000000000000000000000000000000000000000000003e8","0xe63697c800000000000000000000000000000000000000000000000107d3f3f8f2e0e48800000000000000000000000082ef450fb7f06e3294f2f19ed1713b255af0f54100000000000000000000000000000000000000000000000000000000000003e8","0xe63697c80000000000000000000000000000000000000000000000000000000b86bc103200000000000000000000000082ef450fb7f06e3294f2f19ed1713b255af0f54100000000000000000000000000000000000000000000000000000000000003e8","0xe63697c800000000000000000000000000000000000000000000000000000000004456fd00000000000000000000000082ef450fb7f06e3294f2f19ed1713b255af0f54100000000000000000000000000000000000000000000000000000000000003e8","0xe63697c8000000000000000000000000000000000000000000000284a6dad950dab4958000000000000000000000000082ef450fb7f06e3294f2f19ed1713b255af0f54100000000000000000000000000000000000000000000000000000000000003e8"]
["0xE537B5cc158EB71037D4125BDD7538421981E6AA","0xA74d4B67b3368E83797a35382AFB776bAAE4F5C8","0x25212Df29073FfFA7A67399AcEfC2dd75a831A1A","0x5fA5B62c8AF877CB37031e0a3B2f34A78e3C56A6","0x2DfB14E32e2F8156ec15a2c21c3A6c053af52Be8","0xdCD90C7f6324cfa40d7169ef80b12031770B4325","0xa354f35829ae975e850e23e9615b11da1b3dc4de","0xA696a63cc78DfFa1a63E9E50587C197387FF6C7E","0xdA816459F1AB5631232FE5e97a05BBBb94970c95"]
"0x4bd571f8ef1d28be8069ad03021f994255955a735128a2f2e32d1d66b3c6dcfc"
"0x88b49b834bd571f8ef1d28be8069ad03021f994255955a735128a2f2e32d1d66b3c6dcfc"
{"to":"0xEaCD577C3F6c44C3ffA398baaD97aE12CDCFed4a","value":"0x00","data":"0xbd9c75a500000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001c000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000001191b050000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000002bd4a3b1b95b01f2aa61655415a5d3eaacaafdd0000000000000000000000006de73946eab234f1ee61256f10067d713af0e37a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000081758f3361a769016eae4844072fa6d7f828a65100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002488b49b834bd571f8ef1d28be8069ad03021f994255955a735128a2f2e32d1d66b3c6dcfc00000000000000000000000000000000000000000000000000000000"}

2023-10-10 19:51 UTC, villanuevawill commented
GSC Treasury:

"0x6a7612020000000000000000000000008d29be29923b68abfdd21e541b9374737b49cdad000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006d000000000000000000000000000000000000000000000000000000000000006b848d80ff0a00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000006b3f0009b1b33bad0e87454ff05696b1151bfbd208a43f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000ba12222222228d8ba445958a75a0704d566bf2c8000000000000000000000000000000000000000000000134fce8cf3e6219b0ab00ba12222222228d8ba445958a75a0704d566bf2c8000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002648bdb391309b1b33bad0e87454ff05696b1151bfbd208a43f0002000000000000000000a6000000000000000000000000654be0b5556f8eadbc2d140505445fa32715ef2b000000000000000000000000654be0b5556f8eadbc2d140505445fa32715ef2b0000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000418de6227499181b045cadf554030722e460881a0000000000000000000000005a6a4d54456819380173272a5e8e9b9904bdf41b00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000013a94c5d82e9dbe7abf0000000000000000000000000000000000000000000000014e68ee97689dde7e0009b1b33bad0e87454ff05696b1151bfbd208a43f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000ba12222222228d8ba445958a75a0704d566bf2c8000000000000000000000000000000000000000000000000000000000000000000418de6227499181b045cadf554030722e460881a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000418de6227499181b045cadf554030722e460881a00000000000000000000000000000000000000000000013a94c5d82e9dc0c0f900418de6227499181b045cadf554030722e460881a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044884e17f300000000000000000000000000000000000000000000013a94c5d82e9dc0c0f9000000000000000000000000654be0b5556f8eadbc2d140505445fa32715ef2b00418de6227499181b045cadf554030722e460881a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000418de6227499181b045cadf554030722e460881a0000000000000000000000000000000000000000000000000000000000000000005a6a4d54456819380173272a5e8e9b9904bdf41b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044a9059cbb00000000000000000000000082ef450fb7f06e3294f2f19ed1713b255af0f54100000000000000000000000000000000000000000000013be32ec6c6065ea78f00b03c6b351a283bc1cd26b9cf6d7b0c4556013bdb00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000ba12222222228d8ba445958a75a0704d566bf2c8000000000000000000000000000000000000000000000000049146a6e447f5b100ba12222222228d8ba445958a75a0704d566bf2c8000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002648bdb3913b03c6b351a283bc1cd26b9cf6d7b0c4556013bdb0002000000000000000000ab000000000000000000000000654be0b5556f8eadbc2d140505445fa32715ef2b000000000000000000000000654be0b5556f8eadbc2d140505445fa32715ef2b0000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000006325440d014e39736583c165c2963ba99faf14e0000000000000000000000002361102893ccabfb543bc55ac4cc8d6d0824a67e00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000001678b903d8e733d0000000000000000000000000000000000000000000000000333a07a0fa9915b00b03c6b351a283bc1cd26b9cf6d7b0c4556013bdb00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000ba12222222228d8ba445958a75a0704d566bf2c80000000000000000000000000000000000000000000000000000000000000000002361102893ccabfb543bc55ac4cc8d6d0824a67e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b30000000000000000000000002361102893ccabfb543bc55ac4cc8d6d0824a67e0000000000000000000000000000000000000000000000000333a07a0fa9915b002361102893ccabfb543bc55ac4cc8d6d0824a67e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044884e17f30000000000000000000000000000000000000000000000000333a07a0fa9915b000000000000000000000000654be0b5556f8eadbc2d140505445fa32715ef2b002361102893ccabfb543bc55ac4cc8d6d0824a67e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b30000000000000000000000002361102893ccabfb543bc55ac4cc8d6d0824a67e00000000000000000000000000000000000000000000000000000000000000000006325440d014e39736583c165c2963ba99faf14e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044a9059cbb00000000000000000000000082ef450fb7f06e3294f2f19ed1713b255af0f541000000000000000000000000000000000000000000000000049b2c0a4d3804960090ca5cef5b29342b229fb8ae2db5d8f4f894d65200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000ba12222222228d8ba445958a75a0704d566bf2c8000000000000000000000000000000000000000000000020862166ecd3e9745300ba12222222228d8ba445958a75a0704d566bf2c8000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002648bdb391390ca5cef5b29342b229fb8ae2db5d8f4f894d6520002000000000000000000b5000000000000000000000000654be0b5556f8eadbc2d140505445fa32715ef2b000000000000000000000000654be0b5556f8eadbc2d140505445fa32715ef [...]

2023-10-11 09:13 UTC, GregTheGreek approved these changes

2023-10-11 09:13 UTC, merged